name: setup-pnpm
description: "setup pnpm"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v6

    - uses: pnpm/action-setup@v6
      with:
        run_install: true
        cache: true
